In [1]:
# Import libraries and set seed
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

np.random.seed(8)

In [2]:
# Read data 
menstrual = pd.read_csv('data.csv')
menstrual = menstrual.drop(columns = 'id')
menstrual.head()

,day_in_study,sedentary_mins,active_mins,glucose_mean,rhr_mean,minutes_asleep,minutes_awake,sleep_efficiency_mean,sleep_score_overall,sleep_score_revitalization,...,headaches,cramps,sorebreasts,fatigue,sleepissue,moodswing,stress,foodcravings,indigestion,bloating
0,1,753.0,64,5.498958,74.785346,1027.0,26.0,98.0,NaN,NaN,...,High,Very Low/Little,Very Low/Little,High,Low,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
1,2,855.0,74,5.372222,80.407307,77.0,4.0,95.0,NaN,NaN,...,Very High,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
2,3,751.0,159,5.579514,84.686869,502.0,28.0,95.0,NaN,NaN,...,High,Very Low/Little,Very Low/Little,Very High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
3,4,905.0,86,5.206597,83.852219,384.0,65.0,93.0,80.0,22.0,...,Very Low/Little,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
4,5,1430.0,10,5.381597,0.000000,NaN,NaN,NaN,NaN,NaN,...,Very Low/Little,Very Low/Little,Very Low/Little,High,High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little

In [3]:
mlp_data = menstrual[['day_in_study', 'active_mins', 'glucose_mean', 'rhr_mean', 'sleep_score_overall', 'phase', 'lh', 'estrogen', 'sleep_efficiency_mean', 'headaches', 'cramps', 'sorebreasts', 'fatigue', 'sleepissue', 'moodswing', 'stress', 'foodcravings', 'indigestion', 'bloating']]
mlp_data.head()

,day_in_study,active_mins,glucose_mean,rhr_mean,sleep_score_overall,phase,lh,estrogen,sleep_efficiency_mean,headaches,cramps,sorebreasts,fatigue,sleepissue,moodswing,stress,foodcravings,indigestion,bloating
0,1,64,5.498958,74.785346,NaN,Follicular,2.9,94.2,98.0,High,Very Low/Little,Very Low/Little,High,Low,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
1,2,74,5.372222,80.407307,NaN,Follicular,1.2,226.3,95.0,Very High,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
2,3,159,5.579514,84.686869,NaN,Follicular,3.5,276.8,95.0,High,Very Low/Little,Very Low/Little,Very High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
3,4,86,5.206597,83.852219,80.0,Fertility,1.8,322.1,93.0,Very Low/Little,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
4,5,10,5.381597,0.000000,NaN,Fertility,4.6,244.9,NaN,Very Low/Little,Very Low/Little,Very Low/Little,High,High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little

In [4]:
mlp_onehot = pd.get_dummies(mlp_data, drop_first = True, dtype = int)
mlp_onehot.head()

,day_in_study,active_mins,glucose_mean,rhr_mean,sleep_score_overall,lh,estrogen,sleep_efficiency_mean,phase_Follicular,phase_Luteal,...,indigestion_Low,indigestion_Moderate,indigestion_Not at all,indigestion_Very High,indigestion_Very Low/Little,bloating_Low,bloating_Moderate,bloating_Not at all,bloating_Very High,bloating_Very Low/Little
0,1,64,5.498958,74.785346,NaN,2.9,94.2,98.0,1,0,...,0,0,0,0,1,0,0,0,0,1
1,2,74,5.372222,80.407307,NaN,1.2,226.3,95.0,1,0,...,0,0,0,0,1,0,0,0,0,1
2,3,159,5.579514,84.686869,NaN,3.5,276.8,95.0,1,0,...,0,0,0,0,1,0,0,0,0,1
3,4,86,5.206597,83.852219,80.0,1.8,322.1,93.0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,5,10,5.381597,0.000000,NaN,4.6,244.9,NaN,0,0,...,0,0,0,0,1,0,0,0,0,1

In [5]:
print(mlp_data.isna().sum())

day_in_study               0
active_mins                0
glucose_mean             590
rhr_mean                   0
sleep_score_overall      450
phase                      1
lh                       223
estrogen                 224
sleep_efficiency_mean    526
headaches                378
cramps                   378
sorebreasts              378
fatigue                  378
sleepissue               378
moodswing                378
stress                   378
foodcravings             378
indigestion              378
bloating                 378
dtype: int64

In [6]:
# Impute missing values with mean
mlp_data['glucose_mean'] = mlp_data['glucose_mean'].fillna(mlp_data['glucose_mean'].mean())
mlp_data['sleep_score_overall'] = mlp_data['sleep_score_overall'].fillna(mlp_data['glucose_mean'].mean())
mlp_data['lh'] = mlp_data['lh'].fillna(mlp_data['lh'].mean())
mlp_data['estrogen'] = mlp_data['estrogen'].fillna(mlp_data['estrogen'].mean())
mlp_data['sleep_efficiency_mean'] = mlp_data['sleep_efficiency_mean'].fillna(mlp_data['sleep_efficiency_mean'].mean())

print(mlp_data.isna().sum())

day_in_study               0
active_mins                0
glucose_mean               0
rhr_mean                   0
sleep_score_overall        0
phase                      1
lh                         0
estrogen                   0
sleep_efficiency_mean      0
headaches                378
cramps                   378
sorebreasts              378
fatigue                  378
sleepissue               378
moodswing                378
stress                   378
foodcravings             378
indigestion              378
bloating                 378
dtype: int64

/var/folders/pk/m9_wldv960sft_0jzr_j08f40000gn/T/ipykernel_89132/3506805445.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mlp_data['glucose_mean'] = mlp_data['glucose_mean'].fillna(mlp_data['glucose_mean'].mean())
/var/folders/pk/m9_wldv960sft_0jzr_j08f40000gn/T/ipykernel_89132/3506805445.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mlp_data['sleep_score_overall'] = mlp_data['sleep_score_overall'].fillna(mlp_data['glucose_mean'].mean())
/var/folders/pk/m9_wldv960sft_0jzr_j08f40000gn/T/ipykernel_89132/3506805445.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mlp_data['lh'] = mlp_data['lh'].fillna(mlp_data['lh'].mean())
/var/folders/pk/m9_wldv960sft_0jzr_j08f40000gn/T/ipykernel_89132/3506805445.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mlp_data['estrogen'] = mlp_data['estrogen'].fillna(mlp_data['estrogen'].mean())
/var/folders/pk/m9_wldv960sft_0jzr_j08f40000gn/T/ipykernel_89132/3506805445.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mlp_data['sleep_efficiency_mean'] = mlp_data['sleep_efficiency_mean'].fillna(mlp_data['sleep_efficiency_mean'].mean())