In [1]:
# Import libraries and set seed
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', None)
np.random.seed(8)

In [2]:
# Read data 
menstrual = pd.read_csv('data.csv')
menstrual = menstrual.drop(columns = 'id')
menstrual.head()

,day_in_study,sedentary_mins,active_mins,glucose_mean,rhr_mean,minutes_asleep,minutes_awake,sleep_efficiency_mean,sleep_score_overall,sleep_score_revitalization,...,headaches,cramps,sorebreasts,fatigue,sleepissue,moodswing,stress,foodcravings,indigestion,bloating
0,1,753.0,64,5.498958,74.785346,1027.0,26.0,98.0,NaN,NaN,...,High,Very Low/Little,Very Low/Little,High,Low,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
1,2,855.0,74,5.372222,80.407307,77.0,4.0,95.0,NaN,NaN,...,Very High,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
2,3,751.0,159,5.579514,84.686869,502.0,28.0,95.0,NaN,NaN,...,High,Very Low/Little,Very Low/Little,Very High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
3,4,905.0,86,5.206597,83.852219,384.0,65.0,93.0,80.0,22.0,...,Very Low/Little,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
4,5,1430.0,10,5.381597,0.000000,NaN,NaN,NaN,NaN,NaN,...,Very Low/Little,Very Low/Little,Very Low/Little,High,High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little

In [3]:
mlp_data = menstrual[['day_in_study', 'active_mins', 'glucose_mean', 'rhr_mean', 'sleep_score_overall', 'phase', 'lh', 'estrogen', 'sleep_efficiency_mean', 'headaches', 'cramps', 'sorebreasts', 'fatigue', 'sleepissue', 'moodswing', 'stress', 'foodcravings', 'indigestion', 'bloating']]
mlp_data.head()

,day_in_study,active_mins,glucose_mean,rhr_mean,sleep_score_overall,phase,lh,estrogen,sleep_efficiency_mean,headaches,cramps,sorebreasts,fatigue,sleepissue,moodswing,stress,foodcravings,indigestion,bloating
0,1,64,5.498958,74.785346,NaN,Follicular,2.9,94.2,98.0,High,Very Low/Little,Very Low/Little,High,Low,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
1,2,74,5.372222,80.407307,NaN,Follicular,1.2,226.3,95.0,Very High,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
2,3,159,5.579514,84.686869,NaN,Follicular,3.5,276.8,95.0,High,Very Low/Little,Very Low/Little,Very High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
3,4,86,5.206597,83.852219,80.0,Fertility,1.8,322.1,93.0,Very Low/Little,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
4,5,10,5.381597,0.000000,NaN,Fertility,4.6,244.9,NaN,Very Low/Little,Very Low/Little,Very Low/Little,High,High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little

In [9]:
targets = ['headaches', 'cramps', 'sorebreasts', 'fatigue', 'sleepissue', 'moodswing', 'stress', 'foodcravings', 'indigestion', 'bloating']
mlp_bin = mlp_data.copy()
for col in targets:
    mlp_bin[f'bin_{col}'] = (mlp_data[col] != 'Not at all').astype(int)

mlp_bin = mlp_bin.drop(columns=targets)
mlp_bin.head()

,day_in_study,active_mins,glucose_mean,rhr_mean,sleep_score_overall,phase,lh,estrogen,sleep_efficiency_mean,bin_headaches,bin_cramps,bin_sorebreasts,bin_fatigue,bin_sleepissue,bin_moodswing,bin_stress,bin_foodcravings,bin_indigestion,bin_bloating
0,1,64,5.498958,74.785346,NaN,Follicular,2.9,94.2,98.0,1,1,1,1,1,1,1,1,1,1
1,2,74,5.372222,80.407307,NaN,Follicular,1.2,226.3,95.0,1,1,1,1,1,1,1,1,1,1
2,3,159,5.579514,84.686869,NaN,Follicular,3.5,276.8,95.0,1,1,1,1,1,1,1,1,1,1
3,4,86,5.206597,83.852219,80.0,Fertility,1.8,322.1,93.0,1,1,1,1,1,1,1,1,1,1
4,5,10,5.381597,0.000000,NaN,Fertility,4.6,244.9,NaN,1,1,1,1,1,1,1,1,1,1

In [11]:
mlp_onehot = pd.get_dummies(mlp_bin, drop_first = True, dtype = int)
mlp_onehot.head()

,day_in_study,active_mins,glucose_mean,rhr_mean,sleep_score_overall,lh,estrogen,sleep_efficiency_mean,bin_headaches,bin_cramps,...,bin_fatigue,bin_sleepissue,bin_moodswing,bin_stress,bin_foodcravings,bin_indigestion,bin_bloating,phase_Follicular,phase_Luteal,phase_Menstrual
0,1,64,5.498958,74.785346,NaN,2.9,94.2,98.0,1,1,...,1,1,1,1,1,1,1,1,0,0
1,2,74,5.372222,80.407307,NaN,1.2,226.3,95.0,1,1,...,1,1,1,1,1,1,1,1,0,0
2,3,159,5.579514,84.686869,NaN,3.5,276.8,95.0,1,1,...,1,1,1,1,1,1,1,1,0,0
3,4,86,5.206597,83.852219,80.0,1.8,322.1,93.0,1,1,...,1,1,1,1,1,1,1,0,0,0
4,5,10,5.381597,0.000000,NaN,4.6,244.9,NaN,1,1,...,1,1,1,1,1,1,1,0,0,0

In [12]:
print(mlp_onehot.isna().sum())

day_in_study               0
active_mins                0
glucose_mean             590
rhr_mean                   0
sleep_score_overall      450
lh                       223
estrogen                 224
sleep_efficiency_mean    526
bin_headaches              0
bin_cramps                 0
bin_sorebreasts            0
bin_fatigue                0
bin_sleepissue             0
bin_moodswing              0
bin_stress                 0
bin_foodcravings           0
bin_indigestion            0
bin_bloating               0
phase_Follicular           0
phase_Luteal               0
phase_Menstrual            0
dtype: int64

In [13]:
# Impute missing features with mean
mlp_onehot['glucose_mean'] = mlp_onehot['glucose_mean'].fillna(mlp_onehot['glucose_mean'].mean())
mlp_onehot['sleep_score_overall'] = mlp_onehot['sleep_score_overall'].fillna(mlp_onehot['glucose_mean'].mean())
mlp_onehot['lh'] = mlp_onehot['lh'].fillna(mlp_onehot['lh'].mean())
mlp_onehot['estrogen'] = mlp_onehot['estrogen'].fillna(mlp_onehot['estrogen'].mean())
mlp_onehot['sleep_efficiency_mean'] = mlp_onehot['sleep_efficiency_mean'].fillna(mlp_onehot['sleep_efficiency_mean'].mean())

print(mlp_onehot.isna().sum())

day_in_study             0
active_mins              0
glucose_mean             0
rhr_mean                 0
sleep_score_overall      0
lh                       0
estrogen                 0
sleep_efficiency_mean    0
bin_headaches            0
bin_cramps               0
bin_sorebreasts          0
bin_fatigue              0
bin_sleepissue           0
bin_moodswing            0
bin_stress               0
bin_foodcravings         0
bin_indigestion          0
bin_bloating             0
phase_Follicular         0
phase_Luteal             0
phase_Menstrual          0
dtype: int64